### ISSUE TITLE
I am getting this error in mojave 10.14.2 with php7.3 installed on it.

### ISSUE THREAD

**Issue by vimalmistry** [kabel/homebrew-php-ext#10]
`==> Tapping kabel/php-ext
Cloning into '/usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 33 (delta 19), reused 20 (delta 12), pack-reused 0
Unpacking objects: 100% (33/33), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@5.6-enchant.rb
No available formula with the name "php@5.6"
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@5.6-pdo-oci.rb
No available formula with the name "php@5.6"
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@5.6-oci8.rb
No available formula with the name "php@5.6"
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@5.6-imap.rb
No available formula with the name "php@5.6"
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@5.6-snmp.rb
No available formula with the name "php@5.6"
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@5.6-recode.rb
No available formula with the name "php@5.6"
Error: Cannot tap kabel/php-ext: invalid syntax in tap!`

**Comment by vishal-sancheti** [comment]
Same here

**Comment by webflo** [comment]
This is "caused" by https://github.com/Homebrew/homebrew-core/pull/35679. php@5.6 is EOL.

**Comment by vimalmistry** [comment]
@webflo any solution for this?

**Comment by vishal-sancheti** [comment]
try this: https://github.com/v1shky/homebrew-php-ext

**Comment by kabel** [comment]
Fixed at 0f262fcb
