### ISSUE TITLE
Download failed: Invalid Oracle response.

### ISSUE THREAD

**Issue by nohnaimer** [kabel/homebrew-php-ext#15]
Hi,
Update php from 7.3.5 -> 7.3.6

I enter the correct login / password (rechecked the username and password in the browser, that's right) from the account on the oracle site and give this error:
![Снимок экрана 2019-06-03 в 11 00 29](https://user-images.githubusercontent.com/8865830/58785849-093a3b80-85ef-11e9-879f-a42c6ba26460.png)

**Comment by kabel** [comment]
Thanks for the heads up and the log/output capture. Fixed at 9598dec6165f39d8036cb4e6a631b9b17a1cde3e. Always a cat/mouse game with Oracle auth changes.
