### ISSUE TITLE
Unable to update php-imap from 7.3.9 to 7.3.10

### ISSUE THREAD

**Issue by anibuildercc** [kabel/homebrew-php-ext#19]
While I have updated the Hombrew packages, I have got an error in connection with the v1shky/php-ext/php-imap package. I tried to install it by using the v1shky/php-ext, kabel/php-ext and the vishal-sancheti/php-ext repository, with same results. See below:
`brew install php-imap
==> Installing php-imap from v1shky/php-ext
==> Downloading https://www.php.net/distributions/php-7.3.10.tar.xz
Already downloaded: /Users/garai/Library/Caches/Homebrew/downloads/d2bca2ef26a024bc73f18c3fd70f86f37c037119c703ed69f22e2447ca546b50--php-7.3.10.tar.xz
==> /usr/local/opt/php/bin/phpize
==> ./configure --with-php-config=/usr/local/opt/php/bin/php-config --with-imap=/usr/local/opt/imap-uw --with-imap-ssl=/usr/local/opt/openssl --with-kerberos
Last 15 lines from /Users/garai/Library/Logs/Homebrew/php-imap/02.configure:
checking for IMAP support... yes, shared
checking for IMAP Kerberos support... yes
checking for IMAP SSL support... /usr/local/opt/openssl
checking for utf8_mime2text signature... new
checking for U8T_DECOMPOSE... yes
checking for pam_start in -lpam... yes
checking for crypt in -lcrypt... no
checking for krb5-config... /usr/bin/krb5-config
checking for pkg-config... no
checking for OpenSSL version... >= 1.0.1
checking for CRYPTO_free in -lcrypto... yes
checking for SSL_CTX_set_ssl_version in -lssl... yes
checking whether rfc822_output_address_list function present... no
checking whether build with IMAP works... no
configure: error: build test failed. Please check the config.log for details.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/v1shky/homebrew-php-ext/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:259:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:213:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:367:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:275:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:288:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:375:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:371:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:141:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>'`

I have tried to install it from source with same result. Ha I forgotten anything to get the IMAP support for the PHP 7.3? Till PHP 7.3.9 was everything OK, same problem I have never seen.
Thanks for your understanding...

**Comment by kabel** [comment]
I'm not responsible for any of the forks of this tap that are behind. I can only talk about `kabel/php-ext`. Your output shows that you need to `brew update` to get my latest tap changes that include openssl@1.1.

If you need more help, I'll need more info, like the output from `brew doctor` and `brew gist-logs php-imap`

**Comment by anibuildercc** [comment]
Hi Kevin,

thans for your answer and your help. You were right, I needed to use
OpenSSL 1.1 in my macOS 10.14.6, but I have not known that the OpenSSL can
be used with workaround because of the next error message:

brew link --force openssl
Warning: Refusing to link: openssl
Linking keg-only OpenSSL means you may end up linking against the insecure,
deprecated system version while using the headers from the Homebrew version.

I found a solution:

brew update
brew install openssl@1.1
echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

And I can use the OpenSSL 1.1.1. That's perfect!
On the other hand I used the v1shky/php-ext repository instead
of kabel/php-ext one. After I set the OpenSSL path and changed the repo I
could install the php-imap package and the PHP can see and use it after
restarting the Apache.

You're save my life, huge thank you!!!!!!

Anikó
anipostafiok@gmail.com


Kevin Abel <notifications@github.com> ezt írta (időpont: 2019. okt. 3., Cs,
2:02):
