### ISSUE TITLE
Brew tap failes. Custom fork with all 7.1 formulas deleted works

### ISSUE THREAD

**Issue by SamirMokiem** [kabel/homebrew-php-ext#21]
So after a long time trying to get this installed and many errors:

`samir ~ % brew install "kabel/php-ext/php@7.4-imap"
==> Tapping kabel/php-ext
Cloning into '/usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 41 (delta 20), reused 18 (delta 7), pack-reused 0
Unpacking objects: 100% (41/41), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@7.1-recode.rb
No available formula with the name "php@7.1" 
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@7.1-oci8.rb
No available formula with the name "php@7.1" 
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@7.1-enchant.rb
No available formula with the name "php@7.1" 
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@7.1-imap.rb
No available formula with the name "php@7.1" 
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@7.1-pdo-oci.rb
No available formula with the name "php@7.1" 
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/Formula/php@7.1-snmp.rb
No available formula with the name "php@7.1" 
Error: Cannot tap kabel/php-ext: invalid syntax in tap!`

I tried many commands but the output was always the same. 

So i made my own fork and removed all 7.1 formulas and tried to install it via my fork:

`samir@~ % brew install "SamirMokiem/php-ext/php@7.4-imap"
==> Tapping samirmokiem/php-ext
Cloning into '/usr/local/Homebrew/Library/Taps/samirmokiem/homebrew-php-ext'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 35 (delta 14), reused 13 (delta 4), pack-reused 0
Unpacking objects: 100% (35/35), done.
Tapped 18 formulae (89 files, 59.2KB).
==> Installing php-imap from samirmokiem/php-ext
==> Installing dependencies for samirmokiem/php-ext/php-imap: pkg-config and imap-uw
==> Installing samirmokiem/php-ext/php-imap dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2.catalina.bottle.1.tar.gz
==> Downloading from https://akamai.bintray.com/c0/c0a6927c8e404f6db8b14d6644a218b22ddb0d27be1fa0a69d15bf0d9a6875ae?__gda__=exp=1575573813~hmac=ebff359fd80339d6781fa326bff5b33d97a7c53c1fad6952d58048d2ebbd1ee6&response-content-dispos
######################################################################## 100.0%
==> Pouring pkg-config-0.29.2.catalina.bottle.1.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2: 11 files, 623KB
==> Installing samirmokiem/php-ext/php-imap dependency: imap-uw
==> Downloading https://homebrew.bintray.com/bottles/imap-uw-2007f_1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/df/df3de76ba2934218f8f484f2d7e6c760956ba52eecacdb1b623d0b54d872165f?__gda__=exp=1575573816~hmac=3035f73ed23d19b1f75983da7bae852e3f7f5aac8b17cad36a7328f1a92a4eb2&response-content-dispos
######################################################################## 100.0%
==> Pouring imap-uw-2007f_1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/imap-uw/2007f_1: 152 files, 8.9MB
==> Installing samirmokiem/php-ext/php-imap
==> Downloading https://www.php.net/distributions/php-7.4.0.tar.xz
        # -=#=- #     #                                                       
==> /usr/local/opt/php/bin/phpize
==> ./configure --with-php-config=/usr/local/opt/php/bin/php-config --with-imap=/usr/local/opt/imap-uw --with-imap-ssl=/usr/local/opt/openssl@1.1 --with-kerberos
==> make
🍺  /usr/local/Cellar/php-imap/7.4.0: 7 files, 1MB, built in 35 seconds`

And that worked. So whats wrong with the repo/master?

https://i.ibb.co/xXswYGS/image.png

**Comment by kabel** [comment]
Fixed at 499218c167c93b6553053205a4a1b31abe6141ae
