### ISSUE TITLE
PHP hangs after installing imap

### ISSUE THREAD

**Issue by wrabit** [kabel/homebrew-php-ext#24]
After `brew install kabel/php-ext/php@7.4-imap` _any_ php command hangs for several seconds before the command is executed. 

Commenting out the ini and the hang disappears 

```
[imap]
;extension=/usr/local/opt/php-imap/lib/php/20190902/imap.so
```

Any suggestions?

**Comment by kabel** [comment]
I believe this is a known issue with the imap extension. You can try to see help from the php team upstream. This isn't a package issue, so I'm going to close.

This is one of the main reasons why the extension is not included with the homebrew-core. Something in the extension's code is causing a DNS request on the machine's hostname. The hang is likely from a delay in the DNS server resolving the address. I've seen people work around it by adding their machine's name to `/etc/hosts`.

**Comment by wrabit** [comment]
Thanks for the explanation
