### ISSUE TITLE
Please add a 7.4 package

### ISSUE THREAD

**Issue by it-can** [kabel/homebrew-php-ext#28]
Instlaling php-imap now defaults to installing PHP8 version... Same goes for https://github.com/kabel/homebrew-pecl

**Comment by it-can** [comment]
getting this error

```
brew install php@7.4-imap
==> Installing php@7.4-imap from kabel/php-ext
==> Downloading https://www.php.net/distributions/php-7.4.13.tar.xz
Already downloaded: /Library/Caches/Homebrew/downloads/b3afb4902755caaca8804906c64181d32497be5f7c1b4bde72531edad7a2773c--php-7.4.13.tar.xz
Warning: php@7.4-imap: No available formula with the name "php@7.2-recode".
'conflicts_with "php@7.2-recode"' should be removed from php@7.4-imap.rb.
Please report this issue to the kabel/php-ext tap (not Homebrew/brew or Homebrew/core)!
```

**Comment by kabel** [comment]
Lol. More copy/paste errors. I need to document my major bump steps better. Fix coming.

**Comment by it-can** [comment]
thanks for the quick fixes!

**Comment by kabel** [comment]
:shipit: 

![image](https://user-images.githubusercontent.com/675956/100463886-2cce2d00-3092-11eb-95d1-58e64f60b0f4.png)

**Comment by it-can** [comment]
@kabel does https://github.com/kabel/homebrew-pecl also need updating?

**Comment by kabel** [comment]
It does, but we have to wait for CI to regen all the bottles. It's going to take a big chunk of time. Feel free to watch the build progress on the php8 branch

**Comment by Hjsurk** [comment]
Hello,

Just wondering if this problem is the same issue as the one reported above. When I run the following command:
```
brew install kabel/php-ext/php@7.4-imap
```
I will get a message saying php-imap for PHP 8 has already been installed.
```
Warning: kabel/php-ext/php-imap 8.0.0 is already installed and up-to-date
To reinstall 8.0.0, run `brew reinstall php-imap`
```

**Comment by kabel** [comment]
@Hjsurk https://github.com/kabel/homebrew-php-ext#troubleshooting

**Comment by Hjsurk** [comment]
@kabel Is this related to this tap or should I report this issue in homebrew core?

When I run `brew doctor` I get the following output:
```
==> Fetching /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext...
error: Not a valid ref: refs/remotes/origin/main

==> Resetting /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
```

**EDIT:**
Found a solution for my problem. Might be worth adding it to troubleshooting.
```
brew untap kabel/homebrew-php-ext
brew tap kabel/homebrew-php-ext
```
This allowed me to run `brew install kabel/php-ext/php@7.4-imap` without any problems.

**Comment by kabel** [comment]
I've already listed
> If you can an error about the master branch, please try `brew update-reset` to fix the default branch association to main.

If untapping and retapping fixed it for you, great.

**Comment by OskarStark** [comment]
Looks like:
```
brew update-reset
brew untap kabel/homebrew-php-ext
brew tap kabel/homebrew-php-ext
```

works 👍
