### ISSUE TITLE
Installing php@7.4-imap installs php 8

### ISSUE THREAD

**Issue by firefox747** [kabel/homebrew-php-ext#30]
Hi,
i installed php@7.4-imap on macOS Big Sure using Homebrew.
`brew install php@7.4-imap
==> Installing php-imap from kabel/php-ext
==> Downloading https://homebrew.bintray.com/bottles/php-8.0.0_1.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/fb9e9a8db2d02ec3e80882d7f42894dde0c5a3f0d27990a3e365e470ff4ef63c?response-content-disposition=attachment%3Bfilename%3D%22php-8.0.0_1.big_sur.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbn
######################################################################## 100.0%
==> Downloading https://www.php.net/distributions/php-8.0.0.tar.xz
Already downloaded: /Users/kano/Library/Caches/Homebrew/downloads/931327716c2fdbb4db0a09a404f5d0d208381bfa0ed2064764652a4f8578b4ef--php-8.0.0.tar.xz
==> Installing dependencies for kabel/php-ext/php-imap: php
==> Installing kabel/php-ext/php-imap dependency: php
==> Pouring php-8.0.0_1.big_sur.bottle.tar.gz
Warning: php dependency autoconf was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
Unlinking /usr/local/Cellar/php@7.4/7.4.13_1... 25 symlinks removed
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set php_ini /usr/local/etc/php/8.0/php.ini system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set php_dir /usr/local/share/pear system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set doc_dir /usr/local/share/pear/doc system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set ext_dir /usr/local/lib/php/pecl/20200930 system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set bin_dir /usr/local/opt/php/bin system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set data_dir /usr/local/share/pear/data system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set cfg_dir /usr/local/share/pear/cfg system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set www_dir /usr/local/share/pear/htdocs system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set man_dir /usr/local/share/man system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set test_dir /usr/local/share/pear/test system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear config-set php_bin /usr/local/opt/php/bin/php system
==> /usr/local/Cellar/php/8.0.0_1/bin/pear update-channels
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.0/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Summary
🍺  /usr/local/Cellar/php/8.0.0_1: 499 files, 77.8MB
==> Installing kabel/php-ext/php-imap
==> /usr/local/opt/php/bin/phpize
==> ./configure --with-php-config=/usr/local/opt/php/bin/php-config --with-imap=/usr/local/opt/imap-uw --with-imap-ssl=/usr/local/opt/openssl@1.1 --with-kerberos
==> make
🍺  /usr/local/Cellar/php-imap/8.0.0: 8 files, 1MB, built in 39 seconds
==> Caveats
==> php
`
...

It installed PHP8 together with the respective php-imap version. I still need 7.4 though.
Any thoughts?

**Comment by kabel** [comment]
Your tap probably didn't get the branch name switch from master to main. Try `brew update-reset`. If that doesn't work try `brew untap kabel/php-ext && brew tap kabel/php-ext`
