### ISSUE TITLE
PHP IMAP Extension slow on M1

### ISSUE THREAD

**Issue by jamielsharief** [kabel/homebrew-php-ext#34]
When installing PHP Imap extension using PHP 7.4, PHP becomes unusable , there is an 8 second delay to start.

```
$ brew install php@7.4-imap
```

![Kapture 2021-02-19 at 12 20 09](https://user-images.githubusercontent.com/20553479/108500802-9be1a900-72b0-11eb-9331-2f804806b0f7.gif)

I understand this is a known issue and  in general has something to do with DNS query, but i was wondering if anybody has an updated solution to work on the M1.

I have tried running the following command, and adding the name of the system e.g. `macbook.local` to the `/etc/hosts`
```
$ php -i | grep "System"
```

Thanks.

**Comment by kabel** [comment]
Sorry, I can't offer any support. Those kinds of questions are for the php community at-large or the upstream maintainers. I'm just a packager.

If you want more details about what the program is doing for those 8 seconds: `sudo dtruss /usr/local/opt/php@7.4/bin/php -v`
