### ISSUE TITLE
Time lag when "php@7.4-imap" extension enabled

### ISSUE THREAD

**Issue by lezhnev74** [kabel/homebrew-php-ext#35]
I experience a notable time lag when running php with imap extension enabled. I am not sure if this is an appropriate place to file an issue.

MacOS: Big Sur 11.2.1 (20D74)

Installed the php and imap with these commands:
```
brew update

brew upgrade php@7.4

brew tap kabel/php-ext

brew install php@7.4-imap

php -m | grep imap
```

whenever I run php, like in `php -v` it takes around 5 secs before I get the output. Before the installation it used to be instant. 

I wonder if you can give any hints!

Thank you!

**Comment by kabel** [comment]
See https://github.com/kabel/homebrew-php-ext/issues/34#issuecomment-782545190 https://github.com/kabel/homebrew-php-ext/issues/24#issuecomment-611245747

**Comment by lezhnev74** [comment]
Thank you!
