### ISSUE TITLE
php 8.1

### ISSUE THREAD

**Issue by it-can** [kabel/homebrew-php-ext#38]
Can you add php8.1 to your repo? Seems that Homebrew is defaulting to PHP8.2 since a couple of days 

thanks

**Comment by glensc** [comment]
you can probably send pull request yourself and hope @kabel sees it before he makes changes himself.

**Comment by it-can** [comment]
> you can probably send pull request yourself and hope @kabel sees it before he makes changes himself.

yeah Kabel is working on it...
